graph LR
    subgraph Unidades[Unidades y Símbolos]
        g[g - gramo]
        mg[mg - miligramo]
        microg[µg - microgramo]
        mL[mL - mililitro]
    end

    subgraph Formas[Formas Farmacéuticas]
        Aerosol[Aerosol: Tópica, nasal, bucal]
        Capsula[Cápsula: Oral, vaginal]
        Colirio[Colirio: Oftálmica]
        Crema[Crema: Tópica, vaginal, cutánea]
        Elixir[Elíxir: Oral]
        Emulsion[Emulsión: Oral, tópica, parenteral, cutánea]
        Espuma[Espuma: Vaginal, tópica]
        Gas[Gas medicinal: Nasal, bucal]
        Gel[Gel: Bucal, oral, tópica, cutánea]
        Goma[Goma: Bucal, oral]
        Granulado[Granulado: Oral]
        Implante[Implante: Parenteral]
        Jalea[Jalea: Tópica, cutánea, oral]
        Jarabe[Jarabe: Oral]
        Laminilla[Laminilla: Bucal]
        Linimento[Linimento: Tópica, cutánea]
        Locion[Loción: Tópica, cutánea]
        Oblea[Oblea: Oral]
        Ovulo[Óvulo: Vaginal]
        Parche[Parche: Tópica, transdérmica, inhalación, cutánea]
        Pasta[Pasta: Bucal, tópica, cutánea]
        Pastilla[Pastilla: Bucal]
        Polvo[Polvo: Oral, parenteral, tópica]
        Solucion[Solución: Oral, parenteral, oftálmica, tópica, rectal, ótica, nasal, cutánea]
        Supositorio[Supositorio: Rectal, uretral]
        Suspension[Suspensión: Oral, parenteral, rectal, tópica, oftálmica]
        Tableta[Tableta: Oral, bucal, sublingual, vaginal]
        Unguento[Ungüento: Tópica, oftálmica, cutánea]
    end
